# Zhen Lu 2017/03/12 <albert.lz07@gmail.com>

include ../vars.mk

LIB_NAME = libmain

APP_NAME = KIVA_CEMA

FILES    = chem_interface.f90 KIVA_dat.f90 KIVA_read.f90 KIVA_eigen.f90 KIVA_write.f90 KIVA_CEMA.f90

OBJS=$(FILES:.f90=.$(OBJ))

all: $(FILES) $(CREAT_LIBS)

include ../pattern.mk
