# Zhen Lu 2017/03/12 <albert.lz07@gmail.com>

include ../vars.mk

LIB_NAME = libmain

APP_NAME = PSR_CEMA

FILES    = chem_interface.f90 PSR_CEMA.f90

OBJS=$(FILES:.f90=.$(OBJ))

all: $(FILES) $(CREAT_LIBS)

include ../pattern.mk
